export const INCREASE_MONTH_VIEWING = "INCREASE_MONTH_VIEWING";
export const DECREASE_MONTH_VIEWING = "DECREASE_MONTH_VIEWING";
export const CHANGE_WORKOUT_CALENDAR_VIEW = "CHANGE_WORKOUT_CALENDAR_VIEW";
export const ADD_ACTIVITY_TYPE = "ADD_ACTIVITY_TYPE";
export const REMOVE_ACTIVITY_TYPE = "REMOVE_ACTIVITY_TYPE";
export const SELECT_SINGLE_ACTIVITY_DRILLDOWN = "SELECT_SINGLE_ACTIVITY_DRILLDOWN";
export const SELECT_MULTI_ACTIVITY= "SELECT_MULTI_ACTIVITY";
export const CHANGE_TYPE_TOTAL_VIEW = "CHANGE_TYPE_TOTAL_VIEW";
